branches:
  only: 
    - master

matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode10
      script:
        # iOS
        - xcodebuild clean -project "xxHash.xcodeproj" 
        - xcodebuild test -project "xxHash.xcodeproj" -scheme "xxHash-iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X" -configuration Debug
        
        # macOS
        - xcodebuild clean -project "xxHash.xcodeproj" 
        - xcodebuild test -project "xxHash.xcodeproj" -scheme "xxHash-macOS" -destination "platform=OS X" -configuration Debug
        
        # tvOS
        - xcodebuild clean -project "xxHash.xcodeproj" 
        - xcodebuild test -project "xxHash.xcodeproj" -scheme "xxHash-tvOS" -sdk appletvsimulator -destination "OS=12.0,name=Apple TV 4K" -configuration Debug
        
    - os: linux
      language: generic
      dist: xenial
      sudo: false
      addons:
        apt:
          packages:
            - wget
            # Ubuntu needs following packages to build Swift.
            # 
            # Reference:
            # https://github.com/apple/swift#System-Requirements
            - git
            - cmake
            - ninja-build
            - clang
            - python
            - uuid-dev
            - libicu-dev
            - icu-devtools
            - libbsd-dev 
            - libedit-dev
            - libxml2-dev
            - libsqlite3-dev
            - swig
            - libpython-dev
            - libncurses5-dev
            - pkg-config
            - libblocksruntime-dev
            - libcurl4-openssl-dev
            - systemtap-sdt-dev
            - tzdata
            - rsync
      script:
        - wget https://swift.org/builds/swift-4.2-release/ubuntu1604/swift-4.2-RELEASE/swift-4.2-RELEASE-ubuntu16.04.tar.gz
        - tar xvfz swift-4.2-RELEASE-ubuntu16.04.tar.gz
        - export PATH=$(pwd)/swift-4.2-RELEASE-ubuntu16.04/usr/bin:"${PATH}"
        - swift build
        - swift test
